routes/web.php
        Route::post('/update-user', 'Admin\UserController@update_user');

        Route::resource('/feedback', 'Admin\FeedbackController');
        Route::post('/add-feedback', 'Admin\FeedbackController@store');

        Route::resource('/package', 'Admin\PackageController');
        Route::post('/add-package', 'Admin\PackageController@store');
        Route::post('/edit-package', 'Admin\PackageController@edit_package');
        Route::post('/delete-package', 'Admin\PackageController@destroy');
        Route::post('/update-package', 'Admin\PackageController@update');

        Route::resource('/sub-package', 'Admin\SubPackageController');

        Route::resource('/plan-pricing', 'Admin\PlanPricingController');
        Route::post('/add-plan-pricing', 'Admin\PlanPricingController@store');
        Route::post('/edit-plan-pricing', 'Admin\PlanPricingController@edit_plan_pricing');
        Route::post('/edit-plan-pricing1', 'Admin\PlanPricingController@edit_plan_pricing1');
        Route::post('/delete-plan-pricing', 'Admin\PlanPricingController@destroy');
        Route::post('/update-plan-pricing', 'Admin\PlanPricingController@update');

        Route::resource('/offer-discount', 'Admin\OfferDiscountController');
        Route::post('/add-offer-discount', 'Admin\OfferDiscountController@store');
        Route::post('/edit-offer-discount', 'Admin\OfferDiscountController@edit_offer_discount');
        Route::post('/edit-offer-discount2', 'Admin\OfferDiscountController@edit_offer_discount2');
        Route::post('/edit-offer-discount1', 'Admin\OfferDiscountController@edit_offer_discount1');
        Route::post('/delete-offer-discount', 'Admin\OfferDiscountController@destroy');
        Route::post('/update-offer-discount', 'Admin\OfferDiscountController@update');

        Route::resource('/payment-type', 'Admin\PaymentTypeController');
        Route::post('/add-payment-type', 'Admin\PaymentTypeController@store');
        Route::post('/edit-payment-type', 'Admin\PaymentTypeController@edit_payment_type');
        Route::post('/delete-payment-type', 'Admin\PaymentTypeController@destroy');
        Route::post('/update-payment-type', 'Admin\PaymentTypeController@update');



        //from e-billing
        Route::resource('bank', 'Admin\BankController');
        Route::post('bank-edit', 'Admin\BankController@bank_edit')->name('bank-edit');
        Route::post('bank-update', 'Admin\BankController@update')->name('bank-update');
        Route::get('/bank/delete/{id}', 'Admin\BankController@destroy')->name('bank.destroy');

        Route::resource('payment-method', 'Admin\PaymentMethodController');
        Route::post('payment-method-edit', 'Admin\PaymentMethodController@payment_method_edit');
        Route::post('payment-method-update', 'Admin\PaymentMethodController@update');
        Route::get('/payment-method/delete/{id}', 'Admin\PaymentMethodController@destroy')->name('payment-method.destroy');

        Route::resource('account-head', 'Admin\AccountHeadController');

        Route::post('account-head-edit', 'Admin\AccountHeadController@account_head_edit');
        Route::post('account-head-delete', 'Admin\AccountHeadController@destroy');
        Route::post('account-head-update', 'Admin\AccountHeadController@update');

        Route::get('/account-head/delete/{id}', 'Admin\AccountHeadController@destroy')->name('account-head.destroy');


        Route::resource('expense', 'Admin\ExpenseController');
        Route::post('expense-edit', 'Admin\ExpenseController@expense_edit');
        Route::post('expense-delete', 'Admin\ExpenseController@destroy');
        Route::post('expense-update', 'Admin\ExpenseController@update');
        Route::resource('income', 'Admin\IncomeController');
        Route::post('income-edit', 'Admin\IncomeController@income_edit');
        Route::post('income-delete', 'Admin\IncomeController@destroy');
        Route::post('income-update', 'Admin\IncomeController@update');


        Route::resource('employee', 'Admin\EmployeeController');
        Route::post('employee-update', 'Admin\EmployeeController@update1')->name('employee.update');
        Route::post('employees-update', 'Admin\EmployeeController@update');
        Route::post('employee-edit', 'Admin\EmployeeController@employee_edit');
        Route::post('employee-delete', 'Admin\EmployeeController@destroy');
        Route::get('/employee/delete/{id}', 'Admin\EmployeeController@destroy')->name('employee.destroy');



        Route::resource('salary-payroll', 'Admin\SalaryPayrollController');

        Route::post('change-status-payroll', 'Admin\SalaryPayrollController@ChangeStatus')->name('change.status.payroll');

        Route::post('search', 'Admin\SalaryPayrollController@search')->name('salary-payroll.search');
        Route::post('search-due', 'Admin\SalaryDueController@search')->name('salary-due.search');

        Route::post('search-master', 'Admin\SalaryMasterController@search')->name('salary-master.search');
        Route::post('salary-master-update', 'Admin\SalaryMasterController@updateMasterSalary')->name('salary-master.update');
        // Route::post('salary-master-store','Admin\SalaryMasterController@storeEmployee')->name('admin.store.employee.master');

        Route::post('store_salary_master', 'Admin\SalaryMasterController@storeEmployee')->name('store.employee.salary.master');
        Route::post('salary-payroll-edit', 'Admin\SalaryPayrollController@employee_edit');
        Route::post('salary-payroll-edit2', 'Admin\SalaryPayrollController@payroll_edit');
        Route::resource('salary-type', 'Admin\SalaryTypeController');
        Route::get('salary-type-delete/{id}', 'Admin\SalaryTypeController@destroy')->name('salary-type.delete');
        Route::resource('salary-master', 'Admin\SalaryMasterController');

        Route::post('salary-master-month', 'Admin\SalaryMasterController@month')->name('salary-master-month');

        Route::post('salary-master-edit', 'Admin\SalaryMasterController@employee_edit');
        Route::resource('salary-due', 'Admin\SalaryDueController');
        Route::post('salary-due-edit', 'Admin\SalaryDueController@employee_edit');




        Route::resource('lead-management', 'Admin\LeadManagementController');
        Route::post('lead-delete', 'Admin\LeadManagementController@destroy');
        Route::post('lead-edit', 'Admin\LeadManagementController@lead_edit');
        Route::get('lead-management-delete/{id}', 'Admin\LeadManagementController@destroy')->name('lead-management.destroy');
        Route::post('add-estimate', 'Admin\LeadManagementController@add_estimate')->name('add-estimate.store');
        Route::get('estimate-destroy/{id}', 'Admin\LeadManagementController@estimate_destroy')->name('add-estimate.destroy');
        Route::get('estimate-show/{id}', 'Admin\LeadManagementController@estimate_show')->name('add-estimate.show');
        Route::post('add-follow-store', 'Admin\LeadManagementController@add_follow_store')->name('add_follow.store');
        Route::post('add-follow-edit', 'Admin\LeadManagementController@add_follow_edit');
        Route::post('add-follow-update', 'Admin\LeadManagementController@add_follow_update')->name('add_follow.update');

        Route::post('contact-person-store', 'Admin\LeadManagementController@contact_store')->name('contact.store');
        Route::post('contact-person-edit', 'Admin\LeadManagementController@contact_edit');
        Route::post('contact-person-update', 'Admin\LeadManagementController@contact_update')->name('contact.update');

        Route::post('lead-management-search', 'Admin\LeadManagementController@search')->name('lead-management.search');
        Route::get('lead-assignment', 'Admin\LeadManagementController@lead_assignment')->name('lead-assignment');

        Route::post('lead-assignment/{id}', 'Admin\LeadManagementController@lead_assignment_store')->name('lead-management.lead_assignment_store');
        Route::post('lead-assignment-search', 'Admin\LeadManagementController@lead_search')->name('lead-assignment.search');
        Route::get('lead-followup', 'Admin\LeadManagementController@lead_followup')->name('lead-followup');
        Route::post('lead-follow-up-search', 'Admin\LeadManagementController@followup_search')->name('lead-followup.search');
        Route::post('lead-followup', 'Admin\LeadManagementController@lead_followup_store')->name('lead-management.lead_followup_store');
    });




    Route::namespace('Admin\Auth')->group(function () {

        //login route
        Route::get('/login', 'LoginController@showLoginForm')->name('login');
        Route::post('/login', 'LoginController@login')->name('login.store');
        Route::get('/logout', 'LoginController@logout')->name('logout');

        //forget password
        Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::get('/password/email', 'ForgotPasswordController@sendLinkRequestForm')->name('password.email');


        //reset password
        Route::get('/password/reset{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
        Route::get('/password/reset', 'ResetPasswordController@reset')->name('password.update');
    });


    //    Route::namespace('User\Auth',(['verify' => true]))->group(function (){
    Route::namespace('User\Auth')->group(function () {


        //    Route::get('/','LoginController@userShowLoginForm')->name('user-login');
        //        Route::get('/user-login','LoginController@userLoginForm')->name('user.login.form');
        //        Route::post('user-login','LoginController@userLogin')->name('user.login.store');
        //        Route::get('/user-logout','LoginController@userLogout')->name('user.logout');
        //        Route::get('/user-logout/{slug}/logout','LoginController@userLogoutUser')->name('user.logout.user');

        Route::post('/user-login', 'LoginController@login')->name('user.login.store');

app/Models/SalaryType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SalaryType extends Model
{
    //
//    protected $fillable= ['benificial'];
    protected $table = 'salary_types';
    public function salary_master()
    {
        return $this->belongsTo('App\Models\SalaryMaster');
    }
}

resources/views/admin/salary/salary_type_list.blade.php
@extends('admin.layouts.app')
@section('content')

    <div class="row mg-0">
        <div class="col-sm-5">
            <div class="content-header pd-l-5">
                <div>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Human Resources</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Salary Type Setup</li>
                        </ol>
                    </nav>
                    <h4 class="content-title content-title-sm">Salary Type</h4>
                </div>
            </div><!-- content-header -->
        </div><!-- col -->
        <div class="col-sm-0 tx-right col-lg-7">
            @if(Auth::guard('admin')->check())
                 <button type="button" class="btn btn-sm btn-primary mg-t-30 mg-r-20 mg-b-10" data-toggle="modal" data-target="#exampleModalCenter">Add New</button>
            @else
            @can('salary-type-setup-create')
                 <button type="button" class="btn btn-sm btn-primary mg-t-30 mg-r-20 mg-b-10" data-toggle="modal" data-target="#exampleModalCenter">Add New</button>
            @endcan
            @endif
            
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" style="display: none;" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal_ac_head salary_type" role="document">
                    <div class="modal-content">


                            <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalCenterTitle15">SALARY TYPE</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <div class="modal-body text-left salary_payroll">
                            <form action="{{route('salary-type.store')}}" method="post" enctype="multipart/form-data">
                                @csrf
                            <div class="row">
                                <div class="col-md-6 mg-t-5">
                                    Benificial:
                                    <input type="text"  name="benificial" class="form-control" placeholder="Enter benificial like tax" aria-label="Username"  aria-describedby="basic-addon1">
                                </div>
                                <div class="col-md-6 mg-t-5">
                                    Type:
                                    <select class="form-control bd bd-gray-900" name="type" aria-label="Example text with button addon" aria-describedby="button-addon1">
                                        <option value="addition">Addition</option>
                                        <option value="deduction">Deduction</option>
{{--                                        <option value="opel">Manoj</option>--}}
{{--                                        <option value="audi">Pawan</option>--}}
                                    </select>
                                </div>
                            </div><!-- row -->



                            <div class="modal-footer modal-footer_footer justify-content-center pd-b-0">
                                <button  class="btn btn-success mg-r-10">Update</button>
                                <button type="button" class="btn btn-danger mg-r-10" data-dismiss="modal">Cancel</button>
                                <!--   <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                  <button type="button" class="btn btn-primary">Save changes</button> -->
                            </div>
                        </form>
                        </div>


                    </div>
                </div>
            </div>
        </div><!-- col -->
    </div><!-- row -->
    <div class="content-body" style="margin-top: -50px;">
        <div class="component-section">
            <div class="form-group">
                <div class="row pd-l-0">
                    <div class="col-sm-3 pd-r-0">
                        <select class="form-control form-control-sm select2-no-search">
                            <option label="Select Type"></option>
                            <option value="Firefox">Addition</option>
                            <option value="Chrome">Deduction</option>
                        </select>
                    </div>
                    <div class="col-sm-3">
                        <input type="search" class="form-control form-control-sm" placeholder="Search">
                    </div>
                    <div class="col-sm mail-navbar bd-b-0 justify-content-end mg-r-10" style="height: auto;">
                        <div class="d-none d-lg-flex">
                            @if(Auth::guard('admin')->check())
                                 <a href=""><i data-feather="printer"></i></a>
                            @else
                            @can('salary-type-setup-print')
                                 <a href=""><i data-feather="printer"></i></a>
                            @endcan
                            @endif
                            
                            <a href=""><i data-feather="folder"></i></a>

                            @if(Auth::guard('admin')->check())
                                 <a href=""><i class="fas fa-download"></i></a>
                            @else
                            @can('salary-type-setup-download')
                                 <a href=""><i class="fas fa-download"></i></a>
                            @endcan
                            @endif
                            
                        </div>
                    </div>
                </div>
            </div> <!--form-group-->
            <div class="card">
                <table id="example1" class="table">
                    <thead>
                    <tr>
                        <th class="wd-5p">SN.</th>
                        <th class="wd-20p">Benificial</th>
                        <th class="wd-15p">Type</th>
                        <th class="wd-10p">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($salary_type as $key=> $salary_type)
                    <tr>
                        <td>{{++$key}}</td>
                        <td>{{$salary_type->benificial}}</td>
                        <td>
                            @if($salary_type->type=='deduction')
                            <span class="badge badge-pill badge-warning wd-70"> Deduction</span>
                            @else
                            <span class="badge badge-pill badge-success wd-70">Addition</span>
                            @endif
                        </td>
                        <td class="d-md-flex">
{{--                            <div class="mg-r-20" title="View"><a href="../newPages/new-lead-detail.html"><i class="icon ion-clipboard text-success"></i></a></div>--}}
                            @if(Auth::guard('admin')->check())
                                 <div class="mg-r-20" title="Edit"><a href=""><i class="far fa-edit text-warning"></i></a></div>
                            @else
                            @can('salary-type-setup-edit')
                                 <div class="mg-r-20" title="Edit"><a href=""><i class="far fa-edit text-warning"></i></a></div>
                            @endcan
                            @endif

                            @if(Auth::guard('admin')->check())
                                 <div class="mg-r-20" title="Delete"><a href=" " data-toggle="modal" data-target="#exampleModalCenter10"><i class="icon ion-trash-b text-danger"></i></a></div>
                            @else
                            @can('salary-type-setup-delete')
                                 <div class="mg-r-20" title="Delete"><a href=" " data-toggle="modal" data-target="#exampleModalCenter10"><i class="icon ion-trash-b text-danger"></i></a></div>
                            @endcan
                            @endif
                            
{{--                            <div class="mg-r-20" title="Delete"><a href=""><i class="icon ion-trash-b text-danger"></i></a></div>--}}

                            


                            {{--                            fot delete popup--}}

                            <div class="modal fade modal_cust" id="exampleModalCenter10" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" style="display: none;" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered modal_ac_head text-left" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">ARE YOU SURE YOU WANT TO DELETE THIS ??</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">

                                            <div class="conform_del">
                                                <p>After Deletiing This You Will Not Able To Recover It Again. Be Sure Before Deleting.</p>
                                            </div><!-- conform_del -->

                                            <div class="modal-footer modal-footer_footer modal-footer-right text-center conform_del_btn">

                                                <a class="btn btn-success mg-r-10" href="{{route('salary-type.delete',$salary_type->id)}} ">Yes</a>
                                                <button type="button" class="btn btn-danger mg-r-10" data-dismiss="modal">Cancel</button>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>

        </div><!-- component-section -->

    </div><!-- content-body -->

</div><!-- content -->

@endsection